name: Update Codolio Stats

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install requests

      - run: python scripts/generate_stats.py
        env:
          CODOLIO_TOKEN: ${{ secrets.CODOLIO_TOKEN }}

      - name: Commit files
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add .
          git commit -m "Update stats" || echo "No changes"
          git push